auto: true

title: Movoin Blog
author: Allen Luo
description: Something new, Something awesome, Letâ€™s code!
email: movoin@gmail.com
url: https://movoin.com

links:
    weibo: https://weibo.com/movoin
    github: https://github.com/movoin

markdown: kramdown
highlighter: true
permalink: /blog/:year/:title.html

encoding: utf-8
updated_at: 20180907
copyright: 2006-2018 &copy; movoin.com
